export const ZCORPS = {};

// Define constants here, such as:
ZCORPS.caracteristics = {
  'agility': 'ZCORPS.agility',
  'knowledge': 'ZCORPS.knowledge',
  'deftness': 'ZCORPS.deftness',
  'perception': 'ZCORPS.perception',
  'strength': 'ZCORPS.strength',
  'presence': 'ZCORPS.presence'
};

ZCORPS.skills = {
  "acrobatics": "Acrobaties",
  "fight": "Bagarre",
  "contortion": "Contorsion",
  "horseRiding": "Equitation",
  "discretion": "Discrétion",
  "dodge": "Esquive",
  "climbUp": "Grimper",
  "melee": "Mêlée",
  "jump": "Sauter",
  "business": "Affaires",
  "counterfeit": "Contrefaçon",
  "demolition": "Démolition",
  "electronic": "Electronique",
  "erudition": "Erudition",
  "informatic": "Informatique",
  "languages": "Langues",
  "medicine": "Médecine",
  "navigation": "Navigation",
  "security": "Sécurité",
  "occultSciences": "Sciences occultes",
  "firearm": "Arme à feu",
  "throwingWeapon": "Arme de jet",
  "lockPicking": "Crochetage",
  "dexterity": "Dextérité",
  "throw": "Lancer",
  "steering": "Pilotage",
  "fix": "Réparer",
  "artist": "Artiste",
  "camouflage": "Camouflage",
  "search": "Chercher",
  "streetKnowledge": "Connaissance de la rue",
  "games": "Jeux",
  "track": "Pister",
  "survival": "Survie",
  "run": "Courir",
  "endurance": "Endurance",
  "swim": "Nager",
  "lift": "Soulever",
  "charm": "Charmer",
  "order": "Commander",
  "disguise": "Déguisement",
  "dressage": "Dressage",
  "empathy": "Empathie",
  "fraud": "Escroquerie",
  "intimidation": "Intimidation",
  "persuasion": "Persuasion",
  "will": "Volonté"
};